# Generated by Django 5.2.3 on 2026-01-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('category', models.CharField(max_length=16)),
                ('message', models.TextField()),
            ],
        ),
    ]
