# Generated by Django 5.2.3 on 2026-01-07 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackinfo',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 7, 9, 24, 5, 492272)),
        ),
    ]
