# Generated by Django 5.2.3 on 2026-01-10 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackinfo_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackinfo',
            name='department',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackinfo',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
